name: 選挙ドットコム監視

on:
  schedule:
    - cron: "*/10 * * * *"  # 10分ごとに実行
  workflow_dispatch:        # 手動実行も可能

jobs:
  monitor:
    runs-on: ubuntu-latest

    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v3

      - name: Pythonセットアップ
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: requestsインストール
        run: pip install requests

      - name: ページの更新確認
        run: python monitor.py
